global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'flink'
    static_configs:
      - targets: ['jobmanager:9249', 'taskmanager:9249']
        labels:
          env: 'production'
          
  - job_name: 'flink-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jobmanager:8081']
